spring:
  jpa:
    hibernate: 
      ddl-auto: update
    database: mysql
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3000/bookdb?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver